#!/bin/bash
VERSION=1.0.0

loc=$(dirname $(readlink -f "$0")) # Current location
brc=$(find ~/ -type f -name .bashrc) # Location of .bashrc file


# Run all of the setup scripts
setup=$loc/setup/*
for f in $setup
do
eval "$f"
localDir="/scripts/$(basename -a $f)"
if ! grep -q "$localDir" $loc/.gitignore; then
	sudo echo "$localDir" >> $loc/.gitignore
fi
done


# Add all scripts to /bin/
scripts=$loc/scripts/*
filenames=()
for f in $scripts
do
sudo cp "$f" "/bin/"
filenames+=("$(basename -a $f)")
done

createPaths() {
	sudo echo -e "#MooseHelpers\nMooseHelpers VERSION: $VERSION" >> "$brc"
	pathstring="PATH=\""
	for f in ${filenames[@]}
	do
		sudo echo "$f=\"/bin/$f\"" >> "$brc"
		pathstring+="\$$f:"
	done
	pathstring+="\$PATH\""
	sudo echo -e "$pathstring\nexport PATH\n#MooseHelpers" >> "$brc"
}

# If paths not defined, udpate them
if ! grep -qF '#MooseHelpers' "$brc"; then
	createPaths
else
	if [[ $(grep -F "MooseHelpers VERSION:" "$brc") != *"$VERSION" ]]; then
		echo "Version mismatch, updating old paths in $brc"
		if ./internal_helpers/FindAndDelete "#MooseHelpers" "$brc" ; then
			createPaths
		else
			echo "Could not remove old paths in $brc"
		fi
	fi
fi