#!/bin/bash
VERSION=1.3.7 

echo "Installing"

echo "Installing dependencies"

eval "sudo apt install caffeine"
eval "sudo apt-get install mpich"

loc=$(dirname $(readlink -f "$0")) # Current location
brc=$(find ~/ -type f -name .bashrc) # Location of .bashrc file

# Add all scripts to /bin/
echo "Adding scripts to /bin/ directory"
scripts=$loc/scripts/*
filenames=()
for f in $scripts
do
name=$(basename -a $f)
echo "Adding: $name"
sudo cp "$f" "/bin/"
filenames+=("$name")
done

# Create paths and export PATH environment variable in ~/.bashrc
createPaths() {
	sudo echo -e "#MooseHelpers\nMooseHelpers VERSION: $VERSION" >> "$brc"
	pathstring="PATH=\""
	for f in ${filenames[@]}
	do
		sudo echo "$f=\"/bin/$f\"" >> "$brc"
		pathstring+="\$$f:"
	done
	pathstring+="\$PATH\""
	sudo echo -e "$pathstring\nexport PATH\n#MooseHelpers" >> "$brc"
}

# If paths not defined, udpate them
if ! grep -qF '#MooseHelpers' "$brc"; then
	echo "Updating script environment variables"
	createPaths
else # If paths defined, but version not up to date, then rewrite paths
	if [[ $(grep -F "MooseHelpers VERSION:" "$brc") != *"$VERSION" ]]; then
		echo "Version mismatch, updating old paths in $brc"
		# Try deleting old paths
		if "$loc/internal_helpers/FindAndDelete" "#MooseHelpers" "$brc" ; then
			createPaths
		else
			echo "Could not remove old paths in $brc"
		fi
	fi
fi

echo "Done!"