#!/bin/bash
echo "Watching Following Command: $@"

window="--width=600 --height=450"

if $@ ; then
	type="--info"
	output="--text=\"$1 Command terminated successfully\""
else
	type="--error"
	output="--text=\"$1 Command execution failed\""
fi

echo -e "\a"
eval "zenity $type $window $output"
