#!/bin/bash

loc=$(dirname $(readlink -f "$0"))
brc=$(find ~/ -type f -name .bashrc)

sudo cp "$loc/Alert" "/bin/"
sudo cp "$loc/Run" "/bin/"

if ! grep -q 'MooseHelpers' "$brc"; then
	sudo echo -e "\n\n#MooseHelpers\nALERT=\"/bin/Alert\"\nRUN=\"/bin/Run\"\nPATH=\"\$ALERT:\$RUN:\$PATH\"\nexport PATH" >> "$brc"
fi
