#!/bin/bash


loc=$(dirname $(readlink -f "$0")) # Current location
ploc="$loc/../scripts/peacock" # Location of peacock in MooseHelpers/scripts


moose=$(find ~/ -type d -name moose) # Location of moose
peacock=$(find $moose -type f -name peacock) # Location of peacock within moose


# create peacock wrapper
if [ ! -f $ploc ]; then
	sudo echo -e "#!/bin/bash\n\npeacock=\"$peacock\"\neval \"\$peacock \$1\"" > $ploc
	eval "chmod +x $ploc"
fi